title: Government Technology Agency of Singapore | GovTech
url: https://testingsandbox.gov.sg
favicon: /images/symbol 4 magenta.png
colors:
  primary-color: "#b41e8e"
  secondary-color: "#0061af"
  media-colors:
    - title: media-color-one
      color: "#f47920"
    - title: media-color-two
      color: "#00c0f3"
    - title: media-color-three
      color: "#00984e"
    - title: media-color-four
      color: "#0061af"
    - title: media-color-five
      color: "#4d4d4f"
description: The Government Technology Agency (GovTech) is the lead agency
  driving Singapore’s Smart Nation initiative and public sector digital
  transformation. GovTech supports public agencies to manage enterprise IT
  operations and develop new digital products for citizens and businesses.
  GovTech is a Statutory Board under the Smart Nation and Digital Government
  Group (SNDGG) in the Prime Minister’s Office.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dj96ubfmlmhpe.amplifyapp.com
prod: https://master.dj96ubfmlmhpe.amplifyapp.com
resources_name: media
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
